"""Generates markdown session reports."""
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent.parent
REPORTS_DIR = ROOT / "reports"


def generate_report(session_data: dict) -> Path:
    """Write a session report and return its path."""
    REPORTS_DIR.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
    report_path = REPORTS_DIR / f"{timestamp}-session-report.md"

    def section(title: str, items: list) -> list:
        lines = [f"## {title}"]
        if items:
            lines += [f"- {item}" for item in items]
        else:
            lines.append("- (none)")
        return lines + [""]

    lines = [
        f"# Session Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## User Request",
        session_data.get("user_request", "N/A"),
        "",
    ]

    lines += section("Manager Decisions", session_data.get("manager_decisions", []))
    lines += section("Active Agents", session_data.get("active_agents", []))
    lines += section("Tasks Completed", session_data.get("tasks_completed", []))

    lines += ["## Files Changed"]
    files = session_data.get("files_changed", [])
    lines += ([f"- `{f}`" for f in files] if files else ["- (none)"])
    lines += [""]

    lines += [
        "## Tests Run",
        session_data.get("tests_run", "None"),
        "",
    ]

    lines += section("Problems Found", session_data.get("problems", []))
    lines += section("Next Recommended Steps", session_data.get("next_steps", []))

    lines += ["---", "*Generated by Multi-Agent Project Starter*"]

    report_path.write_text("\n".join(lines))
    return report_path
